[project]
name = "entry-below-no-part-13-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "pyotp>=2.9.0",
    "pyqt6>=6.0",
    "pyzmq>=25.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "websocket-client>=1.9.0",
    "keyring>=25.0.0",
]



